package com.api.data_cache.db;

import lombok.Getter;

@Getter
public enum ProductCategory {

    APPAREL_AND_ACCESSORIES,
    ELECTRONICS_AND_ACCESSORIES,
    HOME_AND_KITCHEN_PRODUCTS,
    BEAUTY_AND_PERSONAL_CARE_PRODUCTS,
    HYGIENE_AND_CLEANING_PRODUCTS,
    BABY_PRODUCTS,
    STATIONERY_AND_OFFICE_SUPPLIES,
    PET_PRODUCTS,
    SPORTS_AND_LEISURE,
    HEALTH_AND_WELLNESS_PRODUCTS
}
